In [1]:
from __future__ import print_function, division
import atomicrex
from ase.io import read
from numpy.random import rand

In [2]:
print('Create job object.')
job = atomicrex.Job()

Create job object.


In [3]:
print('Parse XML input file with input parameters'
      ' and potential information.')
job.parse_input_file('main.xml')

Parse XML input file with input parameters and potential information.


In [4]:
print('Switch verbosity to "medium".')
job.set_verbosity(2)

Switch verbosity to "medium".


In [5]:
print('Adding a user-defined structure')
conf = read('aluminum_cell_with_forces.traj')
structure = job.add_ase_structure("Al-ase", conf)
structure.compute_energy(compute_forces=True)
print('Potential energy: {}'.format(structure.get_potential_energy()))
print('Forces:')
for i, force in enumerate(structure.get_forces(), start=1):
    print('{:3}'.format(i), end='')
    print((3*' {:10.6f}').format(*force))
print('')

Adding a user-defined structure
Potential energy: -406.2047401754587
Forces:
  1   0.228919  -0.414564   0.403550
  2   0.334427  -0.379683  -0.069397
  3  -0.378330   0.067553   0.136166
  4  -0.267490  -0.711869   0.103088
  5   0.041314  -0.103023   0.170450
  6  -0.072592   0.667038  -0.564620
  7  -0.084342  -0.047955   0.213211
  8  -0.115677   0.092933   0.172038
  9  -0.064265  -0.366807   0.832819
 10   0.058028   0.272147  -0.303900
 11   0.609703   0.504517  -0.109503
 12  -0.201763  -0.337561   0.344438
 13   0.181338  -0.382344  -0.239885
 14  -0.268741  -0.134157   0.163950
 15  -0.039571   0.339828  -0.169082
 16   0.214491  -0.078753  -0.294276
 17  -0.184247  -0.005419   0.204260
 18   0.071321   0.254455  -0.162130
 19  -0.174279   0.408565  -0.339281
 20   0.191057  -0.715959  -0.307584
 21   0.321434  -0.163228  -0.128408
 22  -0.675297   0.309441  -0.041440
 23   0.219853  -0.117558   0.116172
 24  -0.086599  -0.099193  -0.391948
 25  -0.231826  -0.338388   0.08643

In [6]:
print('Forces:')
for i, force in enumerate(structure.get_forces(), start=1):
    print('{:3}'.format(i), end='')
    print((3*' {:10.6f}').format(*force))
print('')

Forces:
  1   0.228919  -0.414564   0.403550
  2   0.334427  -0.379683  -0.069397
  3  -0.378330   0.067553   0.136166
  4  -0.267490  -0.711869   0.103088
  5   0.041314  -0.103023   0.170450
  6  -0.072592   0.667038  -0.564620
  7  -0.084342  -0.047955   0.213211
  8  -0.115677   0.092933   0.172038
  9  -0.064265  -0.366807   0.832819
 10   0.058028   0.272147  -0.303900
 11   0.609703   0.504517  -0.109503
 12  -0.201763  -0.337561   0.344438
 13   0.181338  -0.382344  -0.239885
 14  -0.268741  -0.134157   0.163950
 15  -0.039571   0.339828  -0.169082
 16   0.214491  -0.078753  -0.294276
 17  -0.184247  -0.005419   0.204260
 18   0.071321   0.254455  -0.162130
 19  -0.174279   0.408565  -0.339281
 20   0.191057  -0.715959  -0.307584
 21   0.321434  -0.163228  -0.128408
 22  -0.675297   0.309441  -0.041440
 23   0.219853  -0.117558   0.116172
 24  -0.086599  -0.099193  -0.391948
 25  -0.231826  -0.338388   0.086436
 26   0.530831   0.048424  -0.403333
 27   0.341594   0.200920   0.

In [7]:
print('Testing some ASE like method calls and properties')
structure = job.structures['Al-ase']
print(' positions')
print(structure.positions)
print(' get_positions()')
print(structure.get_positions())
print(' get_forces()')
print(structure.get_forces())
print(' get_cell()')
print(structure.get_cell())
print(' get_number_of_atoms()')
print(structure.get_number_of_atoms())

Testing some ASE like method calls and properties
 positions
[[-3.98492678e-01 -4.08087682e-01 -9.96224456e-02]
 [-6.65368939e-01  1.58496554e+00  2.03522790e+00]
 [ 1.92614018e+00 -3.11957370e-01  1.76343425e+00]
 [ 1.52233776e+00  1.91464834e+00 -3.81360448e-02]
 [-3.76353681e-01 -6.17827119e-01  3.77766972e+00]
 [-2.45451179e-01  1.25231869e+00  6.24846035e+00]
 [ 1.80889924e+00 -7.91801346e-01  5.75907473e+00]
 [ 1.68380145e+00  1.37330395e+00  4.08461856e+00]
 [-1.26526489e-01 -7.08629922e-01  7.70665956e+00]
 [-3.89087231e-01  1.40456726e+00  1.01351670e+01]
 [ 1.32422427e+00 -8.78220250e-01  1.01126269e+01]
 [ 1.80092503e+00  1.39130444e+00  8.07978827e+00]
 [-5.64223959e-01  3.61639696e+00  1.13072941e-01]
 [-3.41095178e-01  5.58650101e+00  1.98623098e+00]
 [ 1.65039013e+00  3.32016212e+00  2.26021096e+00]
 [ 1.62155452e+00  5.30820706e+00  2.11500325e-01]
 [-3.31552511e-01  3.45137271e+00  4.02597028e+00]
 [-3.66363775e-01  5.32917347e+00  6.11612712e+00]
 [ 1.77097260e+00  3.

In [8]:
print('Handling target forces')
n = structure.get_number_of_atoms()
target_forces = rand(n, 3)
structure.set_target_forces(target_forces)
print('target_forces (1): {}'.format(structure.target_forces[:3]))
print('target_forces (2): {}'.format(structure.get_target_forces()[:3]))

Handling target forces
target_forces (1): [[0.59765936 0.06928507 0.47716186]
 [0.83104738 0.60201688 0.29655145]
 [0.97099529 0.52229898 0.73921374]]
target_forces (2): [[0.59765936 0.06928507 0.47716186]
 [0.83104738 0.60201688 0.29655145]
 [0.97099529 0.52229898 0.73921374]]
